// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzcosczpoaemcibrvotz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6Y29zY3pwb2FlbWNpYnJ2b3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTU4MTQsImV4cCI6MjA2MDg3MTgxNH0.uiR1_3ANjkeowhZA2cws988G5DzVCdIwIkoml7a6pdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);